services:
  # ---------------------------
  # MongoDB (raw data storage with replica set)
  # ---------------------------
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: airflow
      MONGO_INITDB_ROOT_PASSWORD: airflow123
      MONGO_INITDB_DATABASE: air_quality_db
    volumes:
      - ./storage/mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js:ro
      - ./mongo-keyfile:/data/keyfile
      - mongo_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/keyfile"]
    networks:
      - air_quality_net

  # ---------------------------
  # MongoDB Replica Set Initializer
  # ---------------------------
  mongo-init:
    image: mongo:6.0
    container_name: mongo-init
    depends_on:
      - mongo
    volumes:
      - ./storage/init-replica-set.sh:/init-replica-set.sh
    command: bash /init-replica-set.sh
    networks:
      - air_quality_net
    restart: "no"

  # ---------------------------
  # Zookeeper (Kafka dependency)
  # ---------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - air_quality_net

  # ---------------------------
  # Kafka Broker
  # ---------------------------
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # External access
      - "9093:9093" # Internal access (for inter-broker communication)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - air_quality_net

  # ---------------------------
  # Kafka Producer (Air Quality Ingestion)
  # ---------------------------
  producer:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    container_name: producer
    restart: always
    depends_on:
      - kafka
    env_file:
      - .env
    networks:
      - air_quality_net

  # ---------------------------
  # Kafka Consumer (MongoDB Writer)
  # ---------------------------
  consumer:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    container_name: consumer
    restart: always
    depends_on:
      - kafka
      - mongo
      - mongo-init
    env_file:
      - .env
    command: ["python3", "ingestion/consumer.py"]
    networks:
      - air_quality_net

  # ---------------------------
  # Kafka UI (for inspection)
  # ---------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8083:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - air_quality_net

  # ---------------------------
  # MongoDB Kafka Connector (Debezium)
  # ---------------------------
  mongo-connector:
    image: debezium/connect:2.6
    container_name: mongo-connector
    restart: always
    depends_on:
      - kafka
      - mongo
    ports:
      - "8084:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "connect-cluster"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECTORS_PATH: /etc/kafka-connect/connectors
      CONNECT_PLUGIN_PATH: /kafka/connect,/kafka/connect/debezium-connector-mongodb
      CONNECT_REST_ADVERTISED_HOST_NAME: mongo-connector
    volumes:
      - ./streaming/mongo_connector_config.json:/etc/kafka-connect/connectors/mongo_connector_config.json:ro
    networks:
      - air_quality_net

  # ---------------------------
  # Cassandra (analytics sink)
  # ---------------------------
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "air_quality_cluster"
      CASSANDRA_START_RPC: "true"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./storage/cassandra_setup.cql:/docker-entrypoint-initdb.d/cassandra_setup.cql:ro
    networks:
      - air_quality_net

  # ---------------------------
  # Cassandra Consumer (CDC to Cassandra)
  # ---------------------------
  cassandra-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-consumer
    restart: always
    depends_on:
      - kafka
      - cassandra
      - mongo-connector
    env_file:
      - .env
    command: ["python3", "streaming/kafka_consumer.py"]
    networks:
      - air_quality_net

# ---------------------------
# Volumes and network
# ---------------------------
volumes:
  mongo_data:
  cassandra_data:

networks:
  air_quality_net:
    driver: bridge
